version: '3.9'
networks:
  ghosts-network:
    driver: bridge
services:
    threat-hunting-game:
      build:
        context: ../
        target: "vpn"
        dockerfile: Containers/dockerfile
      image: threat-hunting-game:vpn
      container_name: threat-hunting-game-vpn
      ports:
        - '5433:5433'
      networks:
        - ghosts-network
      tty: true
      volumes:
        - ../Containers/Logs:/var/log/threat-hunting-games

    postgres:
      image: postgres
      container_name: ghosts-postgres
      environment:
        POSTGRES_DB: ghosts
        POSTGRES_USER: ghosts
        POSTGRES_PASSWORD: scotty@1
      volumes:
        - ../Containers/Environment_Data/db_data:/var/lib/postgresql/data
        - ../Containers/Environment_Data/spectre_data:/tmp
      logging:
        options:
          max-size: '100m'
          max-file: '5'
      ports:
        - '5432:5432'
      healthcheck:
        test: [ 'CMD-SHELL', 'pg_isready -U ghosts' ]
        interval: 10s
        timeout: 5s
        retries: 10
      networks:
        - ghosts-network
      restart: always

    ghosts-api:
      build:
        context: ../Containers/GHOSTS/src
      container_name: ghosts-api
      depends_on:
        - postgres
      ports:
        - '8080:5000'
      networks:
        - ghosts-network
      restart: always
