# Copyright 2017 Carnegie Mellon University. All Rights Reserved. See LICENSE.md file for terms.

# $ docker build -f Dockerfile-api  . -t ghosts/api

#
#multi-stage target: dev
#
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS dev

ENV ASPNETCORE_URLS=http://*:5000 \
    ASPNETCORE_ENVIRONMENT=DEVELOPMENT

COPY Ghosts.Api/. /app/Ghosts.Api
COPY Ghosts.Domain/. /app/Ghosts.Domain

RUN curl -ks 'http://aia.sei.cmu.edu/ZscalerRootCertificate-2048-SHA256.crt' -o '/usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt'
ENV SSL_CERT_FILE='/usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt'

WORKDIR /app/Ghosts.Api
RUN dotnet publish -c Release -o /app/dist
CMD ["dotnet", "run"]

#
#multi-stage target: prod
#
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS prod
ARG commit
ENV COMMIT=$commit
COPY --from=dev /app/dist /app
WORKDIR /app

ENV GHOSTS_VERSION=6.2.0.0
ENV GHOSTS_API_VERSION=v6
ENV ASPNETCORE_URLS=http://*:5000

EXPOSE 5000
ENV ASPNETCORE_URLS=http://*:5000
CMD ["dotnet", "ghosts.api.dll"]